services:
  ansible:
    build: 
      context: ansible
    user: ${MY_UID}:${MY_GID}
    command: "sleep infinity"
    hostname: ansible
    volumes:
      - ./ansible/src:/etc/ansible
      - ./ansible/id_rsa:/home/ubuntu/.ssh/id_rsa
      - ./ansible/id_rsa.pub:/home/ubuntu/.ssh/id_rsa.pub
  playground:
    build:
      context: playground
    hostname: playground